name = "openlp-service-planner"
main = "src/worker.ts"
compatibility_date = "2026-08-13"
keep_vars = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "openlp-service-planner"
database_id = "607e3f14-9fa8-411b-9603-fe990cf0cf70"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "openlp-service-planner-media"


